/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import pro.dao.CatedraticoDAO;
import pro.dao.EstudiantesDAO;
import pro.dao.UsuariosDAO;
import pro.entities.Catedraticos;
import pro.entities.Estudiantes;
import pro.entities.Usuarios;

/**
 *
 * @author USER
 */
public class FormularioLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormularioNotas
     */
    
    private String rol;

    public FormularioLogin(String rol) {
        initComponents();
        this.rol = rol;
        configurarVentana();
    }

    public FormularioLogin() {
        initComponents();
        configurarVentana();
    }
    
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setBackground(Color.WHITE); // fondo uniforme
        setFont(new Font("Segoe UI", Font.PLAIN, 14));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCorre = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtcontra = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jbEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        jbRegresar.setBackground(new java.awt.Color(177, 134, 156));
        jbRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbRegresar.setForeground(new java.awt.Color(0, 0, 0));
        jbRegresar.setText("Regresar");
        jbRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegresarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("LOGIN");

        txtCorre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCorre.setText("CORREO");

        txtcontra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcontra.setText("CONTRASEÑA");

        jbEnviar.setBackground(new java.awt.Color(197, 134, 156));
        jbEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbEnviar.setForeground(new java.awt.Color(0, 0, 0));
        jbEnviar.setText("ENVIAR");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(txtCorre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcontra)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbEnviar)
                        .addGap(162, 162, 162))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCorre)
                .addGap(18, 18, 18)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtcontra)
                .addGap(18, 18, 18)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jbEnviar)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegresarActionPerformed
        VistaInicial vista = new VistaInicial();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbRegresarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
         String correo = txtcorreo.getText().trim();
    String contraseña = new String(txtContraseña.getPassword());

    // Validar campos vacíos
    if (correo.isEmpty() || contraseña.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Por favor, complete todos los campos.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        Usuarios usuario = usuariosDAO.autenticar(correo, contraseña);

        if (usuario == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Correo o contraseña incorrectos.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rolUsuario = usuario.getRol();

        // Verificar que el rol seleccionado coincida con el del usuario
        if (!rolUsuario.equalsIgnoreCase(this.rol)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El rol seleccionado (" + this.rol + ") no coincide con su tipo de usuario (" + rolUsuario + ").",
                "Acceso denegado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this,
            "Bienvenido " + rolUsuario + ": " + usuario.getNombreUsuario());

        // Redirigir según el rol
        if (rolUsuario.equalsIgnoreCase("catedratico")) {
            CatedraticoDAO catedraticoDAO = new CatedraticoDAO();
            Catedraticos catedratico = catedraticoDAO.buscarPorUsuario(usuario.getIdUsuario());

            if (catedratico != null) {
                new VistaProfesor(catedratico.getIdCatedratico()).setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró información del catedrático en la base de datos.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } 
        else if (rolUsuario.equalsIgnoreCase("estudiante")) {
            EstudiantesDAO estudiantesDAO = new EstudiantesDAO();
            Estudiantes estudiante = estudiantesDAO.buscarPorUsuario(usuario.getIdUsuario());

            if (estudiante != null) {
                new VistaEstudiante(estudiante.getIdEstudiante()).setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró información del estudiante en la base de datos.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } 
        else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Rol no reconocido en la base de datos.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        // Cerrar ventana de login
        this.dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al iniciar sesión:\n" + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbRegresar;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JLabel txtCorre;
    private javax.swing.JLabel txtcontra;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
