/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pro.dao.CalificacionesDAO;
import pro.entities.Calificaciones;

/**
 *
 * @author USER
 */
public class FormularioNotas extends javax.swing.JFrame {

    /**
     * Creates new form PrimerVista
     */
    public FormularioNotas() {
        initComponents();
    }
   // Variables de clase
    private int idEstudiante;
    private int idAsignatura;
    private String nombreEstudiante;

    // Método público para recibir los datos
    public void setDatosEstudiante(int idEstudiante, int idAsignatura, String nombreEstudiante) {
        this.idEstudiante = idEstudiante;
        this.idAsignatura = idAsignatura;
        this.nombreEstudiante = nombreEstudiante;

        // Actualiza el título o etiqueta del formulario
        jlTitulo.setText("Ingresar notas para: " + nombreEstudiante);
    }


    
    private void jcNA1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        jtfExamen1.setEnabled(!jcNA1.isSelected());
    }  

    private void jcNA2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        jtfExamen2.setEnabled(!jcNA2.isSelected());
    }  

    private void jcNA3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        jtfExamenFinal.setEnabled(!jcNA3.isSelected());
    }  

    
     private void configurarVentana() {

        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(Color.WHITE); // fondo uniforme
        setFont(new Font("Segoe UI", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFormularioNotas1 = new javax.swing.JPanel();
        jbRegresar = new javax.swing.JButton();
        jbEnviar = new javax.swing.JButton();
        jpNota1 = new javax.swing.JPanel();
        jcNA1 = new javax.swing.JCheckBox();
        jbExamen1 = new javax.swing.JLabel();
        jtfExamen1 = new javax.swing.JTextField();
        jpNota2 = new javax.swing.JPanel();
        jcNA2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jtfExamen2 = new javax.swing.JTextField();
        jpNotaFinal = new javax.swing.JPanel();
        jcNA3 = new javax.swing.JCheckBox();
        jlExamenFinal = new javax.swing.JLabel();
        jtfExamenFinal = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFormularioNotas1.setBackground(new java.awt.Color(13, 71, 161));
        jpFormularioNotas1.setEnabled(false);

        jbRegresar.setBackground(new java.awt.Color(197, 134, 156));
        jbRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbRegresar.setForeground(new java.awt.Color(0, 0, 0));
        jbRegresar.setText("Regresar");
        jbRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegresarActionPerformed(evt);
            }
        });

        jbEnviar.setBackground(new java.awt.Color(197, 134, 156));
        jbEnviar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbEnviar.setForeground(new java.awt.Color(0, 0, 0));
        jbEnviar.setText("Enviar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jpNota1.setBackground(new java.awt.Color(197, 134, 156));
        jpNota1.setPreferredSize(new java.awt.Dimension(250, 60));

        jcNA1.setText("N.A.");

        jbExamen1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbExamen1.setText("Examen 1");

        jtfExamen1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtfExamen1.setText("Nota ");
        jtfExamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfExamen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNota1Layout = new javax.swing.GroupLayout(jpNota1);
        jpNota1.setLayout(jpNota1Layout);
        jpNota1Layout.setHorizontalGroup(
            jpNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNota1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbExamen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jcNA1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpNota1Layout.setVerticalGroup(
            jpNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcNA1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jbExamen1)
                    .addComponent(jtfExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpNota2.setBackground(new java.awt.Color(197, 134, 156));
        jpNota2.setPreferredSize(new java.awt.Dimension(250, 60));

        jcNA2.setText("N.A");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Examen 2");

        jtfExamen2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtfExamen2.setText("Nota");

        javax.swing.GroupLayout jpNota2Layout = new javax.swing.GroupLayout(jpNota2);
        jpNota2.setLayout(jpNota2Layout);
        jpNota2Layout.setHorizontalGroup(
            jpNota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNota2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jcNA2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpNota2Layout.setVerticalGroup(
            jpNota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNota2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcNA2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jtfExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpNotaFinal.setBackground(new java.awt.Color(197, 134, 156));
        jpNotaFinal.setPreferredSize(new java.awt.Dimension(250, 60));

        jcNA3.setText("N.A");

        jlExamenFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlExamenFinal.setText("Examen Final");

        jtfExamenFinal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtfExamenFinal.setText("Nota");

        javax.swing.GroupLayout jpNotaFinalLayout = new javax.swing.GroupLayout(jpNotaFinal);
        jpNotaFinal.setLayout(jpNotaFinalLayout);
        jpNotaFinalLayout.setHorizontalGroup(
            jpNotaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNotaFinalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlExamenFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jtfExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jcNA3)
                .addGap(16, 16, 16))
        );
        jpNotaFinalLayout.setVerticalGroup(
            jpNotaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNotaFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNotaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcNA3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jlExamenFinal)
                    .addComponent(jtfExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jpFormularioNotas1Layout = new javax.swing.GroupLayout(jpFormularioNotas1);
        jpFormularioNotas1.setLayout(jpFormularioNotas1Layout);
        jpFormularioNotas1Layout.setHorizontalGroup(
            jpFormularioNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormularioNotas1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jpFormularioNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFormularioNotas1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jbRegresar)
                        .addGap(82, 82, 82)
                        .addComponent(jbEnviar))
                    .addComponent(jpNota2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jpNota1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jpNotaFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jpFormularioNotas1Layout.setVerticalGroup(
            jpFormularioNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormularioNotas1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jpNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jpNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jpNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpFormularioNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegresar)
                    .addComponent(jbEnviar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormularioNotas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormularioNotas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfExamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfExamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfExamen1ActionPerformed

    private void jbRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegresarActionPerformed
       VistaProfesor vistaP = new VistaProfesor();
       vistaP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbRegresarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
      try {
        int notasLlenas = 0;
        String tipoNota = "";
        double nota = 0;

        // --- Examen 1 ---
        if (!jcNA1.isSelected() && !jtfExamen1.getText().trim().isEmpty()) {
            notasLlenas++;
            tipoNota = "Examen 1";
            nota = Double.parseDouble(jtfExamen1.getText().trim());
            if (nota < 0 || nota > 30) {
                JOptionPane.showMessageDialog(this, " La nota del Examen 1 debe estar entre 0 y 30.");
                return;
            }
        }

        // --- Examen 2 ---
        if (!jcNA2.isSelected() && !jtfExamen2.getText().trim().isEmpty()) {
            notasLlenas++;
            tipoNota = "Examen 2";
            nota = Double.parseDouble(jtfExamen2.getText().trim());
            if (nota < 0 || nota > 30) {
                JOptionPane.showMessageDialog(this, " La nota del Examen 2 debe estar entre 0 y 30.");
                return;
            }
        }

        // --- Examen Final ---
        if (!jcNA3.isSelected() && !jtfExamenFinal.getText().trim().isEmpty()) {
            notasLlenas++;
            tipoNota = "Examen Final";
            nota = Double.parseDouble(jtfExamenFinal.getText().trim());
            if (nota < 0 || nota > 40) {
                JOptionPane.showMessageDialog(this, " La nota del Examen Final debe estar entre 0 y 40.");
                return;
            }
        }

        if (notasLlenas == 0) {
            JOptionPane.showMessageDialog(this, " Debes ingresar una nota antes de enviar.");
            return;
        }

        if (notasLlenas > 1) {
            JOptionPane.showMessageDialog(this, "️ Solo puedes enviar UNA nota a la vez.");
            return;
        }

        // --- Guardar en BD ---
        CalificacionesDAO dao = new CalificacionesDAO();
        Calificaciones cal = dao.buscarPorEstudianteYAsignatura(idEstudiante, idAsignatura);

        if (cal == null) {
            JOptionPane.showMessageDialog(this, " No se encontró registro de calificación para este estudiante.");
            return;
        }

        switch (tipoNota) {
            case "Examen 1" -> cal.setExamen1((int) nota);
            case "Examen 2" -> cal.setExamen2((int) nota);
            case "Examen Final" -> cal.setExamenFinal((int) nota);
        }

        dao.actualizar(cal);

        JOptionPane.showMessageDialog(this, " Nota registrada con éxito para " + nombreEstudiante);
        this.dispose(); // cerrar el formulario
        new VistaProfesor().setVisible(true);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, " Ingresa un valor numérico válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "️ Error al guardar la nota: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JLabel jbExamen1;
    private javax.swing.JButton jbRegresar;
    private javax.swing.JCheckBox jcNA1;
    private javax.swing.JCheckBox jcNA2;
    private javax.swing.JCheckBox jcNA3;
    private javax.swing.JLabel jlExamenFinal;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpFormularioNotas1;
    private javax.swing.JPanel jpNota1;
    private javax.swing.JPanel jpNota2;
    private javax.swing.JPanel jpNotaFinal;
    private javax.swing.JTextField jtfExamen1;
    private javax.swing.JTextField jtfExamen2;
    private javax.swing.JTextField jtfExamenFinal;
    // End of variables declaration//GEN-END:variables
}
