/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.vista;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import pro.dao.EstudiantesDAO;
import pro.entities.Asignaturas;

/**
 *
 * @author USER
 */
public class VistaEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form VistaEstudiante
     */
    public VistaEstudiante() {
        initComponents();
    }
    
    private int idEstudiante;
    
    public VistaEstudiante(int idEstudiante) {
    initComponents();
    this.idEstudiante = idEstudiante;
    configurarVentana();
    cargarCursosEstudiante(idEstudiante);
    setVisible(true);
    }

    private void cargarNotasCurso(int idEstudiante, int idAsignatura) {
    EstudiantesDAO estudiantesDAO = new EstudiantesDAO();
    List<Object[]> notas = estudiantesDAO.obtenerNotasPorCurso(idEstudiante, idAsignatura);

    DefaultTableModel modeloNotas = (DefaultTableModel) jtNotas.getModel();
    modeloNotas.setRowCount(0); // limpiar tabla

    if (notas == null || notas.isEmpty()) {
        System.out.println("No se encontraron notas para el curso con ID: " + idAsignatura);
        return;
    }

    for (Object[] fila : notas) {
        modeloNotas.addRow(fila);
    }
    }

    private void cargarCursosEstudiante(int idEstudiante) {
    EstudiantesDAO estudiantesDAO = new EstudiantesDAO();
    List<Asignaturas> cursos = estudiantesDAO.obtenerCursosEstudiante(idEstudiante);

    DefaultTableModel modelo = (DefaultTableModel) jtCursos.getModel();
    modelo.setRowCount(0); 

    if (cursos == null || cursos.isEmpty()) {
        System.out.println("No se encontraron cursos para el estudiante con ID " + idEstudiante);
        return;
    }

    for (Asignaturas curso : cursos) {
        System.out.println("Curso encontrado: " + curso.getNombreAsignatura()); // Para depuración
        modelo.addRow(new Object[]{ curso.getNombreAsignatura() });
    }
    }
    
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(Color.WHITE); 
        setFont(new Font("Segoe UI", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpUsuario = new javax.swing.JPanel();
        jbCerrarSesion = new javax.swing.JButton();
        jpCursos = new javax.swing.JPanel();
        jspCursos = new javax.swing.JScrollPane();
        jtCursos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtNotas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jpUsuario.setBackground(new java.awt.Color(197, 134, 156));

        jbCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estudiante.png"))); // NOI18N
        jbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarSesionActionPerformed(evt);
            }
        });

        jtCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cursos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursosMouseClicked(evt);
            }
        });
        jspCursos.setViewportView(jtCursos);
        if (jtCursos.getColumnModel().getColumnCount() > 0) {
            jtCursos.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jpCursosLayout = new javax.swing.GroupLayout(jpCursos);
        jpCursos.setLayout(jpCursosLayout);
        jpCursosLayout.setHorizontalGroup(
            jpCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        jpCursosLayout.setVerticalGroup(
            jpCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jbCerrarSesion))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbCerrarSesion)
                .addGap(18, 18, 18)
                .addComponent(jpCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Examen 1", "Examen 2", "Examen Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtNotas);
        if (jtNotas.getColumnModel().getColumnCount() > 0) {
            jtNotas.getColumnModel().getColumn(0).setResizable(false);
            jtNotas.getColumnModel().getColumn(1).setResizable(false);
            jtNotas.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarSesionActionPerformed
        // Mostrar ventana de confirmación
    int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea cerrar sesión?", 
            "Confirmar salida", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    // Si el usuario confirma, cerrar la ventana
    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose(); // Cierra la ventana actual
    }
    }//GEN-LAST:event_jbCerrarSesionActionPerformed

    private void jtCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursosMouseClicked
        int fila = jtCursos.getSelectedRow();
        if (fila == -1) return;

        String nombreCurso = jtCursos.getValueAt(fila, 0).toString();
        EstudiantesDAO estudiantesDAO = new EstudiantesDAO();

        // 🔹 Obtener todos los cursos del estudiante
        List<Asignaturas> cursos = estudiantesDAO.obtenerCursosEstudiante(idEstudiante);

        // 🔹 Buscar el curso que coincide con el nombre seleccionado
        Asignaturas cursoSeleccionado = cursos.stream()
                .filter(c -> c.getNombreAsignatura().equals(nombreCurso))
                .findFirst()
                .orElse(null);

        if (cursoSeleccionado == null) {
            System.out.println("No se encontró el curso seleccionado.");
            return;
        }

        // 🔹 Mostrar notas del curso seleccionado
        cargarNotasCurso(idEstudiante, cursoSeleccionado.getIdAsignatura());
    }//GEN-LAST:event_jtCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JPanel jpCursos;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JScrollPane jspCursos;
    private javax.swing.JTable jtCursos;
    private javax.swing.JTable jtNotas;
    // End of variables declaration//GEN-END:variables

  
}
